# Generated by Django 4.0.5 on 2022-06-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_pets_country_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('United States', 'Usa'), ('Germany', 'Germany'), ('Ukraine', 'Ukraine'), ('United Kingdom', 'Uk'), ('China', 'China')], default='United States', max_length=30)),
                ('currency', models.CharField(choices=[('USD', 'Dollar'), ('EU', 'Euro'), ('UAH', 'Hryvnia'), ('GBD', 'Pound'), ('CNY', 'Yuan')], default='USD', max_length=3)),
            ],
        ),
    ]
