# Generated by Django 4.0.5 on 2022-07-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_addresses_member_alter_wallets_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Users',
        ),
    ]
