# Generated by Django 4.0.5 on 2022-07-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_rename_members_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='member',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='member',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wallets',
            old_name='member',
            new_name='user',
        ),
    ]
