# Generated by Django 4.0.5 on 2022-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_currency_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='pets',
            name='country',
            field=models.CharField(choices=[('United States', 'Usa'), ('Germany', 'Germany'), ('Ukraine', 'Ukraine'), ('United Kingdom', 'Uk'), ('China', 'China')], default='United States', max_length=30),
        ),
    ]
