# Generated by Django 4.0.5 on 2022-06-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_rename_firstname_members_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Addresses', to='application.members'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wallets', to='application.members'),
        ),
    ]
